# Generated by Django 5.0.1 on 2024-05-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=500)),
                ('total_marks', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'student_master',
                'managed': True,
            },
        ),
    ]
